#!/usr/bin/env python3
"""WSTU Dataset - render docs/SOURCES.md from the generated registry.

Keeps the human-readable source list perfectly in sync with metadata/dataset_registry.json
instead of hand-maintaining 150+ rows.

Usage: python3 scripts/discovery/render_sources.py
"""
from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
META = REPO_ROOT / "metadata"
OUT = REPO_ROOT / "docs" / "SOURCES.md"

HEADER = """# WSTU Dataset - Sources

> Generated by `scripts/discovery/render_sources.py` from `metadata/dataset_registry.json`.
> Do not edit by hand: re-run the generator instead.

Every row below was machine-verified against its primary source. `status` is the pipeline
decision and `training_allowed` follows from it:

| status | meaning | may be trained on |
|---|---|---|
| `verified` | source + provenance + permissive license confirmed | **yes** |
| `evaluation_only` | usable, but the upstream project intends it as a benchmark | **no** (eval splits only) |
| `legal_review` | license `unknown` / `other` / non-commercial / no-derivatives | **no**, until a human clears it |
| `future_candidate` | multimodal; does not fit the v0.1 text schema | no (v0.1) |
| `unknown` | provenance could not be resolved | no |

Columns: `fit` = WSTU fit score (0-100, answer-shape alignment) and
`q` = quality score (0-100, provenance/annotation rigor, never size).
`dup` = duplicate risk from analyst-identified source lineage.

"""


def main() -> int:
    reg = json.loads((META / "dataset_registry.json").read_text(encoding="utf-8"))
    catalog = json.loads((META / "discovery" / "source_catalog.json").read_text(encoding="utf-8"))
    datasets = reg["datasets"]

    lines = [HEADER, f"**Registry:** {reg['counts']['total']} datasets - "
                     f"{reg['counts']['hf_verified']} Hugging Face ids verified.\n"]

    by_domain = defaultdict(list)
    for rec in datasets:
        by_domain[rec["domains"][0]].append(rec)

    lines.append("## Candidate datasets by domain\n")
    for domain in sorted(by_domain, key=lambda d: (-len(by_domain[d]), d)):
        rows = sorted(by_domain[domain], key=lambda r: (-r["wstu_fit_score"], r["id"]))
        lines.append(f"### {domain} ({len(rows)})\n")
        lines.append("| id | name | status | license | role | langs | fit | q | dup | link |")
        lines.append("|---|---|---|---|---|---|---|---|---|---|")
        for r in rows:
            link = r["huggingface_url"] or r["official_url"] or r["github_url"] or ""
            lines.append(
                f"| `{r['id']}` | {r['name']} | {r['status']} | {r['license']} | "
                f"{r['data_role']} | {r['language_count']} | {r['wstu_fit_score']} | "
                f"{r['quality_score']} | {r['duplicate_risk']} | {link} |")
        lines.append("")

    lines.append("## Reference resources (not datasets)\n")
    lines.append("| id | name | kind | organization | url |")
    lines.append("|---|---|---|---|---|")
    for ref in catalog.get("reference_resources", []):
        lines.append(f"| `{ref['id']}` | {ref['name']} | {ref['kind']} | "
                     f"{ref.get('organization','')} | {ref['url']} |")
    lines.append("")

    lines.append("## Catalogs searched\n")
    lines.append("| catalog | url | method | used for |")
    lines.append("|---|---|---|---|")
    for cat in catalog.get("catalogs_searched", []):
        lines.append(f"| {cat['name']} | {cat['url']} | {cat['method']} | {cat['used_for']} |")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[sources] wrote {OUT.relative_to(REPO_ROOT)} "
          f"({len(datasets)} datasets, {len(by_domain)} domains)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())